### ISSUE TITLE
问个比较小白的问题,我把源码放在手机安卓本地上,用谷歌浏览器或者html编辑器显示显示不全

### ISSUE THREAD

**Issue by jojoyoo** [ilovexjp/tfjkt-simulator#1]
电脑版谷歌浏览器一切正常,如果我不部署服务器的话,手机上本地使用应该如何使用呢

**Comment by nannan119** [comment]
挂梯子，创建作者的链接就行了。最好放自己服务器里，搞过域名或者VPs

**Comment by ilovexjp** [comment]
如果想要自己部署又没有服务器的话，可以找些可以访问本地文件的浏览器（好像 Android Chrome 可以访问下载路径里的文件）；或是使用一些可以在本地运行 HTTP 服务器的应用。另外也可以试试一些在线 host 的服务。
