### ISSUE TITLE
健康码下方核酸及行程区域时间格式问题

### ISSUE THREAD

**Issue by alililila** [ilovexjp/tfjkt-simulator#3]
健康码下方的两个查询区域，显示格式如11/02 02时，不会具体到具体分钟，日期中间由/隔开，可否麻烦更新一致。小小细节。不胜感激。
![Screenshot_20221102_151845](https://user-images.githubusercontent.com/117259405/199424637-40841653-ea07-43fb-9b86-617aeb82b3d8.jpg)

**Comment by zjns** [comment]
还有下面那个蓝白色的斜条官方是会循环滚动的，差这点就完美了

**Comment by ilovexjp** [comment]
核酸检测和旅居史的更新日期样式、以及上方的滚动条动画已更新

**Comment by zjns** [comment]
> 核酸检测和旅居史的更新日期样式以及上方的滚动条动画已更新

老哥高效率啊👍

**Comment by Trump2028** [comment]
@uodedcli 求湖南场所码，在之前健康码基础上加一个“场所码”模块（包含场所名称、时间、地址），以及身份证和电话位置微调，如图所示：![image](https://user-images.githubusercontent.com/117327365/199637868-9ed6ab43-9123-49f3-afce-c138044e32f1.jpeg)感谢

**Comment by ilovexjp** [comment]
> @uodedcli 求湖南场所码，在之前健康码基础上加一个“场所码”模块（包含场所名称、时间、地址），以及身份证和电话位置微调，如图所示：![image](https://user-images.githubusercontent.com/117327365/199637868-9ed6ab43-9123-49f3-afce-c138044e32f1.jpeg)感谢

请不要在此发表与本项目无关内容，这种提议可以去 [讨论区](https://github.com/ilovexjp/health-code-index/discussions)
