### ISSUE TITLE
小白问题：iOS 网页顶部 状态栏能否达到“全屏”效果？

### ISSUE THREAD

**Issue by jamsluuuuu** [ilovexjp/tfjkt-simulator#4]
![1111111111](https://user-images.githubusercontent.com/58873674/199651416-937536f8-c4f6-4e61-bad1-3f1c2e323c22.jpg)

如图，真实版本如下

![222222222222](https://user-images.githubusercontent.com/58873674/199651533-30c8b1c1-1cc3-4840-81fd-5bb188479717.jpg)

**Comment by ilovexjp** [comment]
PWA 中不能（只能设定颜色）；网页可以。顶部做成白色是为了在 PWA 中滑下来的时候与导航栏一致，算是一个折中的办法。

**Comment by jamsluuuuu** [comment]
> 

谢谢您的 解答，感谢
