### ISSUE TITLE
checkin场所码界面已经更新

### ISSUE THREAD

**Issue by FreeMantoFree** [ilovexjp/tfjkt-simulator#6]
如图
![up](https://user-images.githubusercontent.com/117552835/200150890-0a51c8eb-b531-476a-a6cc-395903e91ffc.png)
场所信息位置不变，个人信息部分上移，添加了核酸与风险地区查询结果，页面整体缩短

**Comment by FreeMantoFree** [comment]
核酸检测时间和风险地区查询时间未在图上绿色区域显示，实际上应显示时间，烦请关注

**Comment by Ilovedaxian** [comment]
![6FD613DD-AB73-4E41-9BB0-34837CE465C6](https://user-images.githubusercontent.com/117531966/200152036-4d04109b-fcef-4277-8e06-5f2c43ccd4cc.png)

**Comment by Ilovedaxian** [comment]
![53EF5B8E-C914-47D1-8260-9DB9F31E5DE4](https://user-images.githubusercontent.com/117531966/200152095-7ad8d899-7f2a-454d-8510-a4d1b5d9df51.png)
